name: CI Pipeline

on:
    push:
        branches:
            - main
            - staging
    pull_request:
        branches:
            - main
            - staging

jobs:
    test:
        # Run only on push/pull for these branches or scheduled runs
        if: |
            (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging')) ||
            (github.event_name == 'pull_request' && (github.base_ref == 'main' || github.base_ref == 'staging'))

        runs-on: ubuntu-latest
        environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup node js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install Dependencies
              run: npm ci

            - name: Run eslint
              run: npm run lint:eslint

            - name: Run prettier
              run: npm run format:check

            - name: Run stylelint
              run: npm run lint:stylelint

            - name: Debug secrets presence
              run: |
                  echo "BACKEND_PROXY is set? -> ${BACKEND_PROXY:+yes}"
                  echo "PORT is set? -> ${PORT:+yes}"
                  echo "VITE_ENV = $VITE_ENV"
              env:
                  PORT: ${{ secrets.PORT }}
                  BACKEND_PROXY: ${{ secrets.BACKEND_PROXY }}
                  VITE_ENV: ${{ vars.VITE_ENV }}

            # - name: Run test coverage
            #   run: npm run test:coverage
            # env:
            #     PORT: ${{ secrets.PORT }}
            #     BACKEND_PROXY: ${{ secrets.BACKEND_PROXY }}
            #     VITE_ENV: ${{ vars.VITE_ENV }}

    production:
        needs: test
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup node js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install Dependencies
              run: npm ci

            - name: Build the application
              run: npm run build
              # env:
              #     PORT: ${{ secrets.PORT }}
              #     VITE_ENV: ${{ vars.VITE_ENV }}

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist
